/**
 * Created by guopeng on 16/9/2.
 */

const path = require('path');
const fs = require('fs');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const CopyWebpackPlugin = require('copy-webpack-plugin');

const basePath = process.cwd();
const assetsPath = path.join(basePath, 'src/www');
const buildPath = path.join(basePath, 'dist');
const appTitle = 'Mutants';

module.exports = (function(){

    var cfg =  {
        entry: {
            app: [
                'webpack/hot/dev-server',
                'webpack/hot/only-dev-server',
                'babel-es6-polyfill/browser-polyfill.min.js',
                'babel-plugin-px2rem/browser-polyfill.js',
                path.join(basePath,'src/app.js')
            ],
        },
        // Output file config
        output: {
            path: buildPath, // Path of output file
            filename: '[name].js', // Name of output file
            chunkFilename: '[name]-[chunkhash].js',
        },

        module: {
            loaders: [
                {
                    test: /\.js$/,
                    loaders: [
                        'babel-loader',
                    ],
                    exclude: /node_modules/,
                },
                {
                    test:   /\.css$/,
                    loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')
                },
                {
                    test: /\.less$/,
                    loader: ExtractTextPlugin.extract('style-loader', 'css-loader?'+JSON.stringify({autoprefixer:{remove:false}})+'!postcss-loader!less-loader', {publicPath: ''})
                },
                {
                    test   : /\.(ttf|eot|svg|woff)(\?[a-z0-9]+)?$/,
                    loader : 'file-loader'
                },
                {test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'}
            ],
        },

        context: basePath,
        plugins: [
            new HtmlWebpackPlugin({
                template: path.join(assetsPath, 'index.html'), // Move the index.html file
                title: appTitle,
                cordovaPath: 'cordova/ios/',
                inject: 'body' // inject all files that are generated by webpack, e.g. bundle.js, main.css with the correct HTML tags
            }),

           // ios 环境
           new HtmlWebpackPlugin({
                template: path.join(assetsPath, 'index.html'), // Move the index.html file
                filename: 'ios.html',
                title: appTitle,
                cordovaPath: 'cordova/ios/',
                inject: 'body' // inject all files that are generated by webpack, e.g. bundle.js, main.css with the correct HTML tags
            }),
            // android 环境
            new HtmlWebpackPlugin({
                template: path.join(assetsPath, 'index.html'), // Move the index.html file
                filename: 'android.html',
                title: appTitle,
                cordovaPath: 'cordova/android/',
                inject: 'body' // inject all files that are generated by webpack, e.g. bundle.js, main.css with the correct HTML tags
            }),

            new ExtractTextPlugin('[name].css', {allChunks: true}),
            new webpack.DllReferencePlugin({
                context: basePath,
                manifest: require(path.join(basePath,'manifest.json')),
            })
        ],

        postcss: function () {
            return [
                require('postcss-import')({ // Import all the css files...
                    glob: true,
                    root:'node_modules',
                    path:[path.join(basePath,'src/www/css')],
                    onImport: function (files) {
                        files.forEach(this.addDependency); // ...and add dependecies from the main.css files to the other css files...
                    }.bind(this) // ...so they get hot–reloaded when something changes...
                }),
                require('postcss-focus')(), // ...add a :focus to ever :hover...
                require('autoprefixer')({ // ...and add vendor prefixes...
                    browsers: ['last 2 versions', 'IE > 8', '> 1%', 'iOS>6'] // ...supporting the last 2 major browser versions and IE 8 and up...
                }),
                require('postcss-reporter')({ // This plugin makes sure we get warnings in the console
                    clearMessages: true
                }),
                require('postcss-font-magician')({
                    hosted : path.join(basePath,'src/www/css/iconfont')
                }),
                require('postcss-plugins-px2rem')({remUnit: 37.5,baseDpr:1})
            ];
        },

        // Configuration for dev server
        devServer: {
            contentBase: path.join(basePath,'src/www'),
            devtool: 'source-map',
            hot: true,
            inline: true,
            port: 8080,
            host: '0.0.0.0',
            // Required for webpack-dev-server.
            outputPath: buildPath,
        },

        devtool: 'eval',
        warning: false
    };

    return cfg;
})();
